defmodule DdexDeliveryService.Repo.Migrations.AddOrganizationsAndMultitenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:validation_results, "validation_results_delivery_id_fkey")

    alter table(:validation_results) do
      add :organization_id, :uuid, null: false
    end

    drop constraint(:tracks, "tracks_release_id_fkey")

    alter table(:tracks) do
      add :organization_id, :uuid, null: false
    end

    drop_if_exists unique_index(:tracks, [:isrc], name: "tracks_unique_isrc_index")

    drop constraint(:track_artists, "track_artists_track_id_fkey")

    alter table(:track_artists) do
      add :organization_id, :uuid, null: false
    end

    drop_if_exists unique_index(:track_artists, [:track_id, :artist_id],
                     name: "track_artists_unique_track_artist_index"
                   )

    drop constraint(:territory_releases, "territory_releases_release_id_fkey")

    alter table(:territory_releases) do
      add :organization_id, :uuid, null: false
    end

    drop_if_exists unique_index(:territory_releases, [:release_id, :territory_code],
                     name: "territory_releases_unique_release_territory_index"
                   )

    drop constraint(:releases, "releases_delivery_id_fkey")

    drop constraint(:releases, "releases_label_id_fkey")

    alter table(:releases) do
      add :organization_id, :uuid, null: false
    end

    drop_if_exists unique_index(:releases, [:upc], name: "releases_unique_upc_index")

    drop constraint(:release_artists, "release_artists_release_id_fkey")

    alter table(:release_artists) do
      add :organization_id, :uuid, null: false
    end

    drop_if_exists unique_index(:release_artists, [:release_id, :artist_id],
                     name: "release_artists_unique_release_artist_index"
                   )

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:validation_results) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "validation_results_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :delivery_id,
             references(:deliveries,
               column: :id,
               name: "validation_results_delivery_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tracks) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "tracks_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :release_id,
             references(:releases,
               column: :id,
               name: "tracks_release_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:tracks, [:organization_id, :isrc], name: "tracks_unique_isrc_index")

    alter table(:track_artists) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "track_artists_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :track_id,
             references(:tracks,
               column: :id,
               name: "track_artists_track_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:track_artists, [:organization_id, :track_id, :artist_id],
             name: "track_artists_unique_track_artist_index"
           )

    alter table(:territory_releases) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "territory_releases_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :release_id,
             references(:releases,
               column: :id,
               name: "territory_releases_release_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:territory_releases, [:organization_id, :release_id, :territory_code],
             name: "territory_releases_unique_release_territory_index"
           )

    alter table(:releases) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "releases_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :label_id,
             references(:labels,
               column: :id,
               name: "releases_label_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :delivery_id,
             references(:deliveries,
               column: :id,
               name: "releases_delivery_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:releases, [:organization_id, :upc], name: "releases_unique_upc_index")

    alter table(:release_artists) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "release_artists_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :release_id,
             references(:releases,
               column: :id,
               name: "release_artists_release_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:release_artists, [:organization_id, :release_id, :artist_id],
             name: "release_artists_unique_release_artist_index"
           )

    alter table(:organizations) do
      add :name, :text, null: false
      add :slug, :text, null: false
      add :ddex_party_id, :text
      add :status, :text, default: "trial"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    create table(:memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, null: false, default: "member"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "memberships_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "memberships_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:memberships, [:user_id, :organization_id],
             name: "memberships_unique_user_org_index"
           )

    alter table(:labels) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "labels_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    drop_if_exists unique_index(:labels, [:name], name: "labels_unique_name_index")

    create unique_index(:labels, [:organization_id, :name], name: "labels_unique_name_index")

    alter table(:deliveries) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "deliveries_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    drop constraint(:deals, "deals_release_id_fkey")

    alter table(:deals) do
      add :organization_id,
          references(:organizations,
            column: :id,
            name: "deals_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    drop_if_exists unique_index(:deals, [:release_id, :commercial_model, :start_date],
                     name: "deals_unique_release_deal_index"
                   )

    alter table(:deals) do
      modify :release_id,
             references(:releases,
               column: :id,
               name: "deals_release_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:deals, [:organization_id, :release_id, :commercial_model, :start_date],
             name: "deals_unique_release_deal_index"
           )
  end

  def down do
    drop_if_exists unique_index(
                     :deals,
                     [:organization_id, :release_id, :commercial_model, :start_date],
                     name: "deals_unique_release_deal_index"
                   )

    drop constraint(:deals, "deals_release_id_fkey")

    alter table(:deals) do
      modify :release_id,
             references(:releases,
               column: :id,
               name: "deals_release_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:deals, [:release_id, :commercial_model, :start_date],
             name: "deals_unique_release_deal_index"
           )

    drop constraint(:deals, "deals_organization_id_fkey")

    alter table(:deals) do
      remove :organization_id
    end

    drop constraint(:deliveries, "deliveries_organization_id_fkey")

    alter table(:deliveries) do
      remove :organization_id
    end

    drop_if_exists unique_index(:labels, [:organization_id, :name],
                     name: "labels_unique_name_index"
                   )

    create unique_index(:labels, [:name], name: "labels_unique_name_index")

    drop constraint(:labels, "labels_organization_id_fkey")

    alter table(:labels) do
      remove :organization_id
    end

    drop_if_exists unique_index(:memberships, [:user_id, :organization_id],
                     name: "memberships_unique_user_org_index"
                   )

    drop constraint(:memberships, "memberships_user_id_fkey")

    drop constraint(:memberships, "memberships_organization_id_fkey")

    drop table(:memberships)

    drop_if_exists unique_index(:organizations, [:slug], name: "organizations_unique_slug_index")

    alter table(:organizations) do
      remove :updated_at
      remove :inserted_at
      remove :status
      remove :ddex_party_id
      remove :slug
      remove :name
    end

    drop_if_exists unique_index(:release_artists, [:organization_id, :release_id, :artist_id],
                     name: "release_artists_unique_release_artist_index"
                   )

    drop constraint(:release_artists, "release_artists_organization_id_fkey")

    drop constraint(:release_artists, "release_artists_release_id_fkey")

    alter table(:release_artists) do
      modify :release_id,
             references(:releases,
               column: :id,
               name: "release_artists_release_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :organization_id, :uuid
    end

    drop_if_exists unique_index(:releases, [:organization_id, :upc],
                     name: "releases_unique_upc_index"
                   )

    drop constraint(:releases, "releases_organization_id_fkey")

    drop constraint(:releases, "releases_label_id_fkey")

    drop constraint(:releases, "releases_delivery_id_fkey")

    alter table(:releases) do
      modify :delivery_id,
             references(:deliveries,
               column: :id,
               name: "releases_delivery_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :label_id,
             references(:labels,
               column: :id,
               name: "releases_label_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :organization_id, :uuid
    end

    drop_if_exists unique_index(
                     :territory_releases,
                     [:organization_id, :release_id, :territory_code],
                     name: "territory_releases_unique_release_territory_index"
                   )

    drop constraint(:territory_releases, "territory_releases_organization_id_fkey")

    drop constraint(:territory_releases, "territory_releases_release_id_fkey")

    alter table(:territory_releases) do
      modify :release_id,
             references(:releases,
               column: :id,
               name: "territory_releases_release_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :organization_id, :uuid
    end

    drop_if_exists unique_index(:track_artists, [:organization_id, :track_id, :artist_id],
                     name: "track_artists_unique_track_artist_index"
                   )

    drop constraint(:track_artists, "track_artists_organization_id_fkey")

    drop constraint(:track_artists, "track_artists_track_id_fkey")

    alter table(:track_artists) do
      modify :track_id,
             references(:tracks,
               column: :id,
               name: "track_artists_track_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :organization_id, :uuid
    end

    drop_if_exists unique_index(:tracks, [:organization_id, :isrc],
                     name: "tracks_unique_isrc_index"
                   )

    drop constraint(:tracks, "tracks_organization_id_fkey")

    drop constraint(:tracks, "tracks_release_id_fkey")

    alter table(:tracks) do
      modify :release_id,
             references(:releases,
               column: :id,
               name: "tracks_release_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :organization_id, :uuid
    end

    drop constraint(:validation_results, "validation_results_organization_id_fkey")

    drop constraint(:validation_results, "validation_results_delivery_id_fkey")

    alter table(:validation_results) do
      modify :delivery_id,
             references(:deliveries,
               column: :id,
               name: "validation_results_delivery_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :organization_id, :uuid
    end

    drop table(:organizations)

    create unique_index(:release_artists, [:release_id, :artist_id],
             name: "release_artists_unique_release_artist_index"
           )

    alter table(:release_artists) do
      remove :organization_id
    end

    create unique_index(:releases, [:upc], name: "releases_unique_upc_index")

    alter table(:releases) do
      remove :organization_id
    end

    create unique_index(:territory_releases, [:release_id, :territory_code],
             name: "territory_releases_unique_release_territory_index"
           )

    alter table(:territory_releases) do
      remove :organization_id
    end

    create unique_index(:track_artists, [:track_id, :artist_id],
             name: "track_artists_unique_track_artist_index"
           )

    alter table(:track_artists) do
      remove :organization_id
    end

    create unique_index(:tracks, [:isrc], name: "tracks_unique_isrc_index")

    alter table(:tracks) do
      remove :organization_id
    end

    alter table(:validation_results) do
      remove :organization_id
    end
  end
end
