defmodule DdexDeliveryService.Repo.Migrations.AddRoleAndConnections do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:organizations) do
      add :role, :text
    end

    create table(:connections, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "active"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :supplier_id,
          references(:organizations,
            column: :id,
            name: "connections_supplier_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :recipient_id,
          references(:organizations,
            column: :id,
            name: "connections_recipient_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:connections, [:supplier_id, :recipient_id],
             name: "connections_unique_supplier_recipient_index"
           )
  end

  def down do
    drop_if_exists unique_index(:connections, [:supplier_id, :recipient_id],
                     name: "connections_unique_supplier_recipient_index"
                   )

    drop constraint(:connections, "connections_supplier_id_fkey")

    drop constraint(:connections, "connections_recipient_id_fkey")

    drop table(:connections)

    alter table(:organizations) do
      remove :role
    end
  end
end
