defmodule DdexDeliveryService.Repo.Migrations.UpsertIdentities do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:deals, [:release_id, :commercial_model, :start_date],
             name: "deals_unique_release_deal_index"
           )
  end

  def down do
    drop_if_exists unique_index(:deals, [:release_id, :commercial_model, :start_date],
                     name: "deals_unique_release_deal_index"
                   )
  end
end
