defmodule DdexDeliveryService.Repo.Migrations.AddApiKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :key_hash, :text, null: false
      add :key_prefix, :text, null: false
      add :scopes, {:array, :text}, default: fragment("'{read}'::text[]")
      add :expires_at, :utc_datetime_usec
      add :last_used_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "api_keys_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:api_keys, [:organization_id, :key_hash],
             name: "api_keys_unique_key_hash_index"
           )
  end

  def down do
    drop_if_exists unique_index(:api_keys, [:organization_id, :key_hash],
                     name: "api_keys_unique_key_hash_index"
                   )

    drop constraint(:api_keys, "api_keys_organization_id_fkey")

    drop table(:api_keys)
  end
end
