defmodule DdexDeliveryService.Repo.Migrations.AddCatalogAndIngestion do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:validation_results, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :severity, :text, null: false
      add :rule_code, :text
      add :message, :text
      add :field_name, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :delivery_id, :uuid, null: false
    end

    create table(:tracks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :title, :text, null: false
      add :isrc, :text
      add :duration, :bigint
      add :track_number, :bigint
      add :disc_number, :bigint, default: 1
      add :display_artist, :text
      add :ddex_resource_reference, :text
      add :p_line, :map
      add :c_line, :map

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :release_id, :uuid, null: false
    end

    create table(:track_artists, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, default: "main"
      add :sequence_number, :bigint

      add :track_id,
          references(:tracks,
            column: :id,
            name: "track_artists_track_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :artist_id, :uuid, null: false
    end

    create table(:territory_releases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :territory_code, :text, null: false
      add :title, :text
      add :display_artist, :text
      add :label_name, :text
      add :genre, :text
      add :sub_genre, :text
      add :language_code, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :release_id, :uuid, null: false
    end

    create table(:releases, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:tracks) do
      modify :release_id,
             references(:releases,
               column: :id,
               name: "tracks_release_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:tracks, [:isrc], name: "tracks_unique_isrc_index")

    alter table(:territory_releases) do
      modify :release_id,
             references(:releases,
               column: :id,
               name: "territory_releases_release_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:territory_releases, [:release_id, :territory_code],
             name: "territory_releases_unique_release_territory_index"
           )

    alter table(:releases) do
      add :title, :text, null: false
      add :subtitle, :text
      add :release_type, :text, default: "album"
      add :upc, :text
      add :catalog_number, :text
      add :grid, :text
      add :release_date, :date
      add :original_release_date, :date
      add :duration, :bigint
      add :display_artist, :text
      add :p_line, :map
      add :c_line, :map
      add :parental_warning, :text, default: "unknown"
      add :status, :text, default: "active"
      add :ddex_release_reference, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :label_id, :uuid
      add :delivery_id, :uuid
    end

    create table(:release_artists, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :role, :text, default: "main"
      add :sequence_number, :bigint

      add :release_id,
          references(:releases,
            column: :id,
            name: "release_artists_release_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :artist_id, :uuid, null: false
    end

    create table(:labels, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:releases) do
      modify :label_id,
             references(:labels,
               column: :id,
               name: "releases_label_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:labels) do
      add :name, :text, null: false
      add :ddex_party_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:labels, [:name], name: "labels_unique_name_index")

    create table(:deliveries, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:validation_results) do
      modify :delivery_id,
             references(:deliveries,
               column: :id,
               name: "validation_results_delivery_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:releases) do
      modify :delivery_id,
             references(:deliveries,
               column: :id,
               name: "releases_delivery_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:releases, [:upc], name: "releases_unique_upc_index")

    alter table(:deliveries) do
      add :source, :text, default: "upload"
      add :status, :text, null: false, default: "received"
      add :ern_version, :text
      add :message_id, :text
      add :error_summary, :text
      add :original_filename, :text
      add :completed_at, :utc_datetime

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:deals, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :commercial_model, :text
      add :usage_types, {:array, :text}, default: []
      add :territory_codes, {:array, :text}, default: []
      add :start_date, :date
      add :end_date, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :release_id,
          references(:releases,
            column: :id,
            name: "deals_release_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create table(:artists, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:track_artists) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "track_artists_artist_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:track_artists, [:track_id, :artist_id],
             name: "track_artists_unique_track_artist_index"
           )

    alter table(:release_artists) do
      modify :artist_id,
             references(:artists,
               column: :id,
               name: "release_artists_artist_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:release_artists, [:release_id, :artist_id],
             name: "release_artists_unique_release_artist_index"
           )

    alter table(:artists) do
      add :name, :text, null: false
      add :isni, :text
      add :ddex_party_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:artists, [:name], name: "artists_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:artists, [:name], name: "artists_unique_name_index")

    alter table(:artists) do
      remove :updated_at
      remove :inserted_at
      remove :ddex_party_id
      remove :isni
      remove :name
    end

    drop_if_exists unique_index(:release_artists, [:release_id, :artist_id],
                     name: "release_artists_unique_release_artist_index"
                   )

    drop constraint(:release_artists, "release_artists_artist_id_fkey")

    alter table(:release_artists) do
      modify :artist_id, :uuid
    end

    drop_if_exists unique_index(:track_artists, [:track_id, :artist_id],
                     name: "track_artists_unique_track_artist_index"
                   )

    drop constraint(:track_artists, "track_artists_artist_id_fkey")

    alter table(:track_artists) do
      modify :artist_id, :uuid
    end

    drop table(:artists)

    drop constraint(:deals, "deals_release_id_fkey")

    drop table(:deals)

    alter table(:deliveries) do
      remove :updated_at
      remove :inserted_at
      remove :completed_at
      remove :original_filename
      remove :error_summary
      remove :message_id
      remove :ern_version
      remove :status
      remove :source
    end

    drop_if_exists unique_index(:releases, [:upc], name: "releases_unique_upc_index")

    drop constraint(:releases, "releases_delivery_id_fkey")

    alter table(:releases) do
      modify :delivery_id, :uuid
    end

    drop constraint(:validation_results, "validation_results_delivery_id_fkey")

    alter table(:validation_results) do
      modify :delivery_id, :uuid
    end

    drop table(:deliveries)

    drop_if_exists unique_index(:labels, [:name], name: "labels_unique_name_index")

    alter table(:labels) do
      remove :updated_at
      remove :inserted_at
      remove :ddex_party_id
      remove :name
    end

    drop constraint(:releases, "releases_label_id_fkey")

    alter table(:releases) do
      modify :label_id, :uuid
    end

    drop table(:labels)

    drop constraint(:release_artists, "release_artists_release_id_fkey")

    drop table(:release_artists)

    alter table(:releases) do
      remove :delivery_id
      remove :label_id
      remove :updated_at
      remove :inserted_at
      remove :ddex_release_reference
      remove :status
      remove :parental_warning
      remove :c_line
      remove :p_line
      remove :display_artist
      remove :duration
      remove :original_release_date
      remove :release_date
      remove :grid
      remove :catalog_number
      remove :upc
      remove :release_type
      remove :subtitle
      remove :title
    end

    drop_if_exists unique_index(:territory_releases, [:release_id, :territory_code],
                     name: "territory_releases_unique_release_territory_index"
                   )

    drop constraint(:territory_releases, "territory_releases_release_id_fkey")

    alter table(:territory_releases) do
      modify :release_id, :uuid
    end

    drop_if_exists unique_index(:tracks, [:isrc], name: "tracks_unique_isrc_index")

    drop constraint(:tracks, "tracks_release_id_fkey")

    alter table(:tracks) do
      modify :release_id, :uuid
    end

    drop table(:releases)

    drop table(:territory_releases)

    drop constraint(:track_artists, "track_artists_track_id_fkey")

    drop table(:track_artists)

    drop table(:tracks)

    drop table(:validation_results)
  end
end
