defmodule DdexDeliveryService.Repo.Migrations.AddStoredFiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:stored_files, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :bucket, :text, null: false
      add :key, :text, null: false
      add :filename, :text, null: false
      add :content_type, :text
      add :byte_size, :bigint
      add :checksum_sha256, :text
      add :file_type, :text, null: false
      add :status, :text, null: false, default: "uploading"
      add :purged_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "stored_files_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :delivery_id,
          references(:deliveries,
            column: :id,
            name: "stored_files_delivery_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:stored_files, "stored_files_organization_id_fkey")

    drop constraint(:stored_files, "stored_files_delivery_id_fkey")

    drop table(:stored_files)
  end
end
