defmodule DdexDeliveryService.Repo.Migrations.AddSftpKeysAndDeliverySource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sftp_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :public_key, :text, null: false
      add :fingerprint, :text, null: false
      add :active, :boolean, null: false, default: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "sftp_keys_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:sftp_keys, [:fingerprint], name: "sftp_keys_unique_fingerprint_index")
  end

  def down do
    drop_if_exists unique_index(:sftp_keys, [:fingerprint],
                     name: "sftp_keys_unique_fingerprint_index"
                   )

    drop constraint(:sftp_keys, "sftp_keys_organization_id_fkey")

    drop table(:sftp_keys)
  end
end
